version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build:
    resource_class: small
    executor:
      name: node/default
      tag: '14.18.2'
    steps:
      - checkout
      - node/install-packages
      - run: npm run test
